### ISSUE TITLE
Browser extension - Swarm extension architecture

### ISSUE THREAD

**Issue by agazso** [ethersphere/js-team-zenhub#5]
We are creating a Chrome browser extension as part of our research effort to figure out a way to handle bzz links and pages securely.

**Comment by vojtechsimetka** [comment]
@nugaon TODO
- create issues for the sprint tasks and assign to this epic

**Comment by nugaon** [comment]
I forgot to add #17 Fake URL but it resolved on the prev week

**Comment by nugaon** [comment]
also [#15](https://github.com/ethersphere/swarm-extension/issues/15) messaging

**Comment by nugaon** [comment]
The BZZ protocol had to be redesigned to prepare for utilizing security context: https://github.com/ethersphere/swarm-extension/issues/28

**Comment by nugaon** [comment]
Compilation was broken and it was a obsticle of the developing, but it was being resolved https://github.com/ethersphere/swarm-extension/issues/30
